// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdcIlj_JAvJ1_Xfliy6UaAohYM3GJ3d9o',
    appId: '1:791479616125:web:0498b5409dfc6fdf70a714',
    messagingSenderId: '791479616125',
    projectId: 'test-592ee',
    authDomain: 'test-592ee.firebaseapp.com',
    storageBucket: 'test-592ee.appspot.com',
    measurementId: 'G-71XXDQZ03T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAET9EBhhPFvSUcrMKcepL_SsMwX6fO-jA',
    appId: '1:791479616125:android:89c950b4798ac42670a714',
    messagingSenderId: '791479616125',
    projectId: 'test-592ee',
    storageBucket: 'test-592ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDCH5Gxdb5kqRz1hDBc0rUx8m0gzQL-DU',
    appId: '1:791479616125:ios:3d6ccdd8c340b1b670a714',
    messagingSenderId: '791479616125',
    projectId: 'test-592ee',
    storageBucket: 'test-592ee.appspot.com',
    iosClientId: '791479616125-ckknmgteh27kkmo84jp987p4hooqtg48.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDCH5Gxdb5kqRz1hDBc0rUx8m0gzQL-DU',
    appId: '1:791479616125:ios:bc748cb5139941b170a714',
    messagingSenderId: '791479616125',
    projectId: 'test-592ee',
    storageBucket: 'test-592ee.appspot.com',
    iosClientId: '791479616125-e5ol64v9s8pmsgvtj5mqba5opo6ji1b8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAplication1',
  );
}
